name: storm
channels:
  - conda-forge
dependencies:
  - python=3.7
  - appmode
  - rasterio
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - nodejs
  - dask
  - distributed
  - gcsfs
  - s3fs
  - bokeh
  - holoviews
  - panel
  - geoviews
  - hvplot
  - rasterio
  - geoviews
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - jupyter
  - jupyterlab
  - ipywidgets
  - ipyleaflet
  - graphviz
  - xarray

